FROM node:26-alpine as builder

# Node environment
ENV NODE_ENV development

# Install git (required for VS Code source control in Dev Container)
RUN apk add --no-cache git openssh-client

# Create destination directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install dependencies
COPY package*.json .
RUN npm install && npm cache clean --force

EXPOSE 3001

VOLUME /usr/src/app

CMD ["npm", "run", "dev"]
