FROM node:25-alpine as builder

# Node environment
ENV NODE_ENV production

# Create destination directory
RUN mkdir -p /usr/src/app

# Make the '/usr/src/app' folder the current working directory
WORKDIR /usr/src/app

# Copy both 'package.json' and 'package-lock.json' (if available)
COPY package*.json .

# Install dependencies
RUN npm install && npm cache clean --force

# Copy project files and folders to the current working directory (i.e. 'app' folder)
COPY . .

EXPOSE 3001

CMD ["npm", "run", "start"]
